name: happy_feet_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.19.0+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # support for MIDI
  tonic: ^0.2.3
  #flutter_midi: ^1.0.2
  flutter_ogg_piano: ^1.1.3
  #audioplayers: ^0.20.1
  soundpool: ^2.2.0
  #flutter_blue: 0.8.0
  #flutter_blue:
  #  git:
  #    url: https://github.com/boskokg/flutter_blue/
  #    ref: 0.11.0
  flutter_reactive_ble: 5.0.0
  rxdart: ^0.27.1
  #rxdart: 0.26.0
  flutter_launcher_icons: ^0.9.2
  circular_buffer: ^0.9.1
  package_info_plus: ^1.3.0
  get: ^4.3.8
  url_launcher: ^6.0.6
  provider: ^5.0.0
  intl: ^0.17.0
  #permission_handler: ^8.3.0
  synchronized: ^3.0.0
  device_display_brightness: 0.0.6
  google_fonts: ^2.2.0
#  sprintf: ^6.0.0
#  firebase_auth: ^3.1.2
#  cloud_firestore: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3
  flutter_native_splash: ^1.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_v14.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
# google fonts folder
    - google_fonts/
 # percussion sounds as both .mp3 (for iOS version) and .ogg (for Android version_   
    - assets/sounds/fatkick.ogg
    - assets/sounds/kick_drum2.ogg
    - assets/sounds/snare_drum.ogg
    - assets/sounds/high_hat.ogg
    - assets/sounds/cowbell.ogg
    - assets/sounds/tambourine.ogg
    - assets/sounds/fingersnap.ogg
    - assets/sounds/sidestick.ogg
    - assets/sounds/shaker.ogg
    - assets/sounds/woodblock2.ogg
    - assets/sounds/lodrytom.ogg
    - assets/sounds/hidrytom.ogg
    - assets/sounds/circlebrush.ogg
    - assets/sounds/vibraslap.ogg
    - assets/sounds/fatkick.mp3
    - assets/sounds/kick_drum2.mp3
    - assets/sounds/snare_drum.mp3
    - assets/sounds/high_hat.mp3
    - assets/sounds/cowbell.mp3
    - assets/sounds/tambourine.mp3
    - assets/sounds/fingersnap.mp3
    - assets/sounds/sidestick.mp3
    - assets/sounds/shaker.mp3
    - assets/sounds/woodblock2.mp3
    - assets/sounds/lodrytom.mp3
    - assets/sounds/hidrytom.mp3
    - assets/sounds/circlebrush.mp3
    - assets/sounds/vibraslap.mp3
#    - assets/sounds/Bass74MapleJazzA1.ogg
#    - assets/sounds/Bass74MapleJazzA1_5sTrimEnvelope.ogg
#    - assets/sounds/Bass74MapleJazzA1_5sTrimEnvelope2dB.ogg
#    - assets/sounds/Bass74MapleJazzA1_1sTrim.ogg
# bass notes from E1 (00.mp3) through E3 (23.mp3)
    - assets/sounds/00.mp3
    - assets/sounds/01.mp3
    - assets/sounds/02.mp3
    - assets/sounds/03.mp3
    - assets/sounds/04.mp3
    - assets/sounds/05.mp3
    - assets/sounds/06.mp3
    - assets/sounds/07.mp3
    - assets/sounds/08.mp3
    - assets/sounds/09.mp3
    - assets/sounds/10.mp3
    - assets/sounds/11.mp3
    - assets/sounds/12.mp3
    - assets/sounds/13.mp3
    - assets/sounds/14.mp3
    - assets/sounds/15.mp3
    - assets/sounds/16.mp3
    - assets/sounds/17.mp3
    - assets/sounds/18.mp3
    - assets/sounds/19.mp3
    - assets/sounds/20.mp3
    - assets/sounds/21.mp3
    - assets/sounds/22.mp3
    - assets/sounds/23.mp3
    - assets/sounds/00.ogg
    - assets/sounds/01.ogg
    - assets/sounds/02.ogg
    - assets/sounds/03.ogg
    - assets/sounds/04.ogg
    - assets/sounds/05.ogg
    - assets/sounds/06.ogg
    - assets/sounds/07.ogg
    - assets/sounds/08.ogg
    - assets/sounds/09.ogg
    - assets/sounds/10.ogg
    - assets/sounds/11.ogg
    - assets/sounds/12.ogg
    - assets/sounds/13.ogg
    - assets/sounds/14.ogg
    - assets/sounds/15.ogg
    - assets/sounds/16.ogg
    - assets/sounds/17.ogg
    - assets/sounds/18.ogg
    - assets/sounds/19.ogg
    - assets/sounds/20.ogg
    - assets/sounds/21.ogg
    - assets/sounds/22.ogg
    - assets/images/icon.png
    - assets/images/Logo_v14.png

