name: happy_feet_app
description: Companion app for HappyFeet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.33.0+33

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_ogg_piano: ^1.1.3
  soundpool: ^2.3.0
  flutter_bass:
    #git:
    #  url: https://github.com/JimTompkins/flutter_bass/
    #  ref: master
    # Note: using git to load the plugin gave an error:
    #   Module 'flutter_bass' not found
    path: ../flutter_bass
  flutter_blue_plus: ^1.3.1
  #flutter_reactive_ble: 5.0.2
  rxdart: ^0.27.1
  flutter_launcher_icons: ^0.9.2
  circular_buffer: ^0.9.1
  package_info_plus: ^1.3.0
  get: ^4.3.8
  url_launcher: ^6.0.6
  provider: ^5.0.0
  intl: ^0.17.0
  permission_handler: ^9.2.0
  synchronized: ^3.0.0
  device_display_brightness: 0.0.6
  google_fonts: 2.2.0
  shared_preferences: ^2.0.13
  flutter_spinbox: ^0.8.0
  dropdown_button2: ^1.8.2
  introduction_screen: ^3.0.2
  flutter_email_sender: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.3
  flutter_native_splash: ^1.3.2
  ffi: ^2.0.1
  ffigen: ^7.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_v14.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: IrishGrover
      fonts:
        - asset: assets/fonts/IrishGrover-Regular.ttf

  assets:
# google fonts folder
    - google_fonts/
# percussion sounds 
    - assets/sounds/fatkick.mp3
    - assets/sounds/kick_drum2.mp3
    - assets/sounds/snare_drum.mp3
    - assets/sounds/high_hat.mp3
    - assets/sounds/cowbell.mp3
    - assets/sounds/tambourine.mp3
    - assets/sounds/fingersnap.mp3
    - assets/sounds/sidestick.mp3
    - assets/sounds/shaker.mp3
    - assets/sounds/woodblock2.mp3
    - assets/sounds/lodrytom.mp3
    - assets/sounds/hidrytom.mp3
    - assets/sounds/circlebrush.mp3
    - assets/sounds/vibraslap.mp3
    - assets/sounds/tambourine.mp3
# bass notes from E1 (00.mp3) through D#3 (23.mp3)
    - assets/sounds/00.mp3
    - assets/sounds/01.mp3
    - assets/sounds/02.mp3
    - assets/sounds/03.mp3
    - assets/sounds/04.mp3
    - assets/sounds/05.mp3
    - assets/sounds/06.mp3
    - assets/sounds/07.mp3
    - assets/sounds/08.mp3
    - assets/sounds/09.mp3
    - assets/sounds/10.mp3
    - assets/sounds/11.mp3
    - assets/sounds/12.mp3
    - assets/sounds/13.mp3
    - assets/sounds/14.mp3
    - assets/sounds/15.mp3
    - assets/sounds/16.mp3
    - assets/sounds/17.mp3
    - assets/sounds/18.mp3
    - assets/sounds/19.mp3
    - assets/sounds/20.mp3
    - assets/sounds/21.mp3
    - assets/sounds/22.mp3
    - assets/sounds/23.mp3
    # sound files for metronome tone
    - assets/sounds/click.mp3
    # images
    - assets/images/icon.png
    - assets/images/Logo_v14.png
    - assets/images/overview.jpg
    - assets/images/charging.jpg
    - assets/images/flutter.png
    - assets/images/fullscreen.jpeg
    - assets/images/img1.jpeg
    - assets/images/img2.jpeg
    - assets/images/img3.jpeg


