import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Connect',
'Disconnect': 'Disconnect',
'MODE': 'MODE',
'Play mode': 'Play mode',
'NOTES': 'NOTES',
'1st note': '1st note',
'2nd note': '2nd note',
'Happy Feet - Grooves': 'Happy Feet - Grooves',
'DEFINE GROOVE': 'DEFINE GROOVE',
'Beats/measure': 'Beats/measure',
'Measures': 'Measures',
'Voices': 'Voices',
'1': '1',
'2': '2',
'Backbeat': 'Backbeat',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock',
'Save groove': 'Save groove',
'Load groove': 'Load groove',
'Happy Feet - Bass': 'Happy Feet - Bass',
'DEFINE BASS GROOVE': 'DEFINE BASS GROOVE',
'Key of': 'Key of',
'Tones:': 'Tones:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Choose "-" for no note, or Roman numerals I through VII plus flats for tones',
'Not set': 'Not set',
'Happy Feet - Info Menu': 'Happy Feet - Info Menu',
'Model number:': 'Model number:',
'Result:': 'Result:',
'Error:': 'Error:',
'Awaiting result': 'Awaiting result',
'Show HappyFeet homepage': 'Show HappyFeet homepage',
'Happy Feet - Settings Menu': 'Happy Feet - Settings Menu',
'Sensitivity': 'Sensitivity',
'Less': 'Less',
'More': 'More',
'Reset sensitivity to default': 'Reset sensitivity to default',
'Happy Feet - Save Groove': 'Happy Feet - Save Groove',
'Enter groove name:': 'Enter groove name:',
'Enter a description of the groove:': 'Enter a description of the groove:',
'Happy Feet - Load Groove': 'Happy Feet - Load Groove',
'Saved grooves:': 'Saved grooves:',
'Loaded groove': 'Loaded groove',
'Load status': 'Load status',
'Missing or invalid file name:': 'Missing or invalid file name:',
'Notice': 'Notice',
'Status': 'Status',
'already connected': 'already connected',
'back beat mode can only be used with even number of beats per measure.': 'back beat mode can only be used with even number of beats per measure.',
'beats disabled': 'beats disabled',
'beats enabled': 'beats enabled',
'connect to Bluetooth first': 'connect to Bluetooth first',
'connecting to Bluetooth': 'connecting to Bluetooth',
'disconnecting Bluetooth': 'disconnecting Bluetooth',
'groove saved': 'groove saved',
'not connected': 'not connected',
'Single Note': 'Single Note',
'Alternating Notes': 'Alternating Notes',
'Dual Notes': 'Dual Notes',
'Groove': 'Groove',
'Bass': 'Bass',
'Sequence error:': 'Sequence error:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'A beat was missed, possibly due to a lost Bluetooth notify message',
'Bluetooth status': 'Bluetooth status',
'This device does not support Bluetooth': 'This device does not support Bluetooth',
'Authorize the HappyFeet app to use Bluetooth and location': 'Authorize the HappyFeet app to use Bluetooth and location',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth is turned off.  Please turn it on',
'Enable location services': 'Enable location services',
'Found Happy Feet!  Connecting': 'Found Happy Feet!  Connecting',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': 'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?',
'Connected!': 'Connected!',
'Connection failed with with error': 'Connection failed with with error',
'Disconnecting': 'Disconnecting',
'Change language': 'Change language',
'Firmware revision:': 'Firmware revision:',
'Disconnecting since no beats detected for 30 minutes': 'Disconnecting since no beats detected for 30 minutes',
'Audio test mode': 'Audio test mode',
'You cannot use audio test mode if connected.': 'You cannot use audio test mode if connected.',
'Audio test mode enabled.': 'Audio test mode enabled.',
'Audio test mode disabled.': 'Audio test mode disabled.',
'In audio test mode, tap the music note button to play the next note.': 'In audio test mode, tap the music note button to play the next note.',
'Loading percussion sounds.': 'Loading percussion sounds.',
'Loading bass sounds.': 'Loading bass sounds.',
},
'fr': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Connecter',
'Disconnect': 'Déconnecter',
'MODE': 'MODE',
'Play mode': 'Mode de jeu',
'NOTES': 'REMARQUES',
'1st note': '1ère note',
'2nd note': '2ème note',
'Happy Feet - Grooves': 'Happy Feet - Grooves',
'DEFINE GROOVE': 'Définir le groove',
'Beats/measure': 'Battements / mesure',
'Measures': 'Mesures',
'Voices': 'Voix',
'1': '1',
'2': '2',
'Backbeat': 'Backbeat',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Choisissez "-" pour aucune note, B pour tambour de basse, K pour tambour de coup de pied, S pour tambour au piège, H pour chymbal Hi-chapeau, t pour la tambourin, c pour Cowbell, F pour le doigt, r pour le tir à bord, A pour Shaker , W pour woodblock',
'Save groove': 'Sauvegarder le groove',
'Load groove': 'Charger un groove',
'Happy Feet - Bass': 'Happy Feet - Basse',
'DEFINE BASS GROOVE': 'Définir le groove de basse',
'Key of': 'Clé de',
'Tones:': 'Tons:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Choisissez "-" pour aucune note, ou bien un chiffre romain de I à VII + dièse pour les tons',
'Not set': 'Pas encore défini',
'Happy Feet - Info Menu': 'Happy Feet - Menu Info',
'Model number:': 'Numéro de modèle:',
'Result:': 'Résultat:',
'Error:': 'Erreur:',
'Awaiting result': 'En attente du résultat',
'Show HappyFeet homepage': 'Montrer la page d\'accueil de Happy Feet',
'Happy Feet - Settings Menu': 'Happy Feet - Menu Paramètres',
'Sensitivity': 'Sensibilité',
'Less': 'Moins',
'More': 'Suite',
'Reset sensitivity to default': 'Réinitialiser la sensibilité à la valeur par défaut',
'Happy Feet - Save Groove': 'Happy Feet - sauvegarder le groove',
'Enter groove name:': 'Entrez le nom du groove:',
'Enter a description of the groove:': 'Entrez une description du groove:',
'Happy Feet - Load Groove': 'Happy Feet - Charger un groove',
'Saved grooves:': 'Grooves sauvegardés:',
'Loaded groove': 'Groove chargé',
'Load status': 'État de la charge',
'Missing or invalid file name:': 'Nom du fichier manquant ou non valide:',
'Notice': 'Avis',
'Status': 'Statut',
'already connected': 'Déjà connecté',
'back beat mode can only be used with even number of beats per measure.': 'Le mode "Back Beat" ne peut être utilisé qu\'avec un nombre pair de battements par mesure.',
'beats disabled': 'Beats désactivé',
'beats enabled': 'Beats activés',
'connect to Bluetooth first': 'Connectez-vous à Bluetooth d\'abord',
'connecting to Bluetooth': 'Connexion au Bluetooth',
'disconnecting Bluetooth': 'Déconnecter Bluetooth',
'groove saved': 'groove sauvé',
'not connected': 'pas connecté',
'Single Note': 'Note unique',
'Alternating Notes': 'Notes alternées',
'Dual Notes': 'Double notes',
'Groove': 'Groove',
'Bass': 'Basse',
'Sequence error:': 'Erreur de séquence:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'Un battement a été manqué, éventuellement due à un message de notification Bluetooth perdu',
'Bluetooth status': 'Statut Bluetooth',
'This device does not support Bluetooth': 'Cet appareil ne prend pas en charge Bluetooth',
'Authorize the HappyFeet app to use Bluetooth and location': 'Autoriser l\'application Happyfeet pour utiliser Bluetooth et Emplacement',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth est éteint. S\'il vous plaît allumez-le',
'Enable location services': 'Activer les services de localisation',
'Found Happy Feet!  Connecting': 'Trouvé Happy Feet! De liaison',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': 'Vous ne pouvez pas trouver des Happy Feet! Êtes-vous le propriétaire? Est-ce à proximité? Est-ce chargé?',
'Connected!': 'Connecté!',
'Connection failed with with error': 'La connexion a échoué avec une erreur',
'Disconnecting': 'Déconnexion',
'Change language': 'Changer de langue',
'Firmware revision:': 'Révision du micrologiciel:',
'Disconnecting since no beats detected for 30 minutes': 'Déconnexion depuis aucun battement détecté pendant 30 minutes',
'Audio test mode': 'Mode test audio',
'You cannot use audio test mode if connected.': 'Vous ne pouvez pas utiliser le mode test audio si connecté.',
'Audio test mode enabled.': 'Mode de test audio activé.',
'Audio test mode disabled.': 'Mode de test audio désactivé.',
'In audio test mode, tap the music note button to play the next note.': 'En mode test audio, appuyez sur le bouton Musique Note pour lire la note suivante.',
'Loading percussion sounds.': 'Chargement des sons de percussion.',
'Loading bass sounds.': 'Chargement de basses sons.',
},
'de': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Verbinden',
'Disconnect': 'Trennen',
'MODE': 'MODUS',
'Play mode': 'Spiel-Modus',
'NOTES': 'ANMERKUNGEN',
'1st note': '1. Note',
'2nd note': '2. Note',
'Happy Feet - Grooves': 'Happy Feet - Grooves',
'DEFINE GROOVE': 'Groove definieren',
'Beats/measure': 'Beats / Takt',
'Measures': 'Takt',
'Voices': 'Voices.',
'1': '1',
'2': '2',
'Backbeat': 'Backbeat',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Wählen Sie "-" für keine Note, B für Bassdrum, K für Kick Drum, S für Snare Drum, H für Hi-Hat-Becken, T für Tamburin, C für Cowbell, F für Fingersnap, R für Rim-Schuss, A für Shaker , W für Woodblock',
'Save groove': 'Groove speichern',
'Load groove': 'Groove laden',
'Happy Feet - Bass': 'Happy Feet - Bass',
'DEFINE BASS GROOVE': 'Bass Groove definieren',
'Key of': 'Schlüssel von',
'Tones:': 'Töne:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Wählen Sie "-" für keine Note oder römische Ziffern I bis VII plus \'b\' für Töne',
'Not set': 'Nicht eingestellt',
'Happy Feet - Info Menu': 'Happy Feet - Info-Menü',
'Model number:': 'Modell-Nr:',
'Result:': 'Ergebnis:',
'Error:': 'Fehler:',
'Awaiting result': 'Warten auf das Ergebnis',
'Show HappyFeet homepage': 'HappyFeet-Homepage anzeigen.',
'Happy Feet - Settings Menu': 'Happy Feet - Einstellungen Menü',
'Sensitivity': 'Erkennungsschwelle',
'Less': 'Weniger',
'More': 'Mehr',
'Reset sensitivity to default': 'Sensibilität auf Standardeinstellung zurücksetzen',
'Happy Feet - Save Groove': 'Happy Feet - Groove speichern',
'Enter groove name:': 'Groovename eingeben:',
'Enter a description of the groove:': 'Geben Sie eine Beschreibung der Groove ein:',
'Happy Feet - Load Groove': 'Happy Feet - Groove laden',
'Saved grooves:': 'Gespeicherte Grooves:',
'Loaded groove': 'Geladene Grovves',
'Load status': 'Status laden',
'Missing or invalid file name:': 'Fehlender oder ungültiger Dateiname:',
'Notice': 'Notiz',
'Status': 'Status',
'already connected': 'schon verbunden',
'back beat mode can only be used with even number of beats per measure.': 'Der Back-Beat-Modus kann nur mit geraden Anzahl von Beats pro Takt verwendet werden.',
'beats disabled': 'Beats ausgeschaltet',
'beats enabled': 'Beats aktiviert',
'connect to Bluetooth first': 'Verbinden Sie sich zuerst mit Bluetooth',
'connecting to Bluetooth': 'Verbindung zu Bluetooth',
'disconnecting Bluetooth': 'Bluetooth trennen',
'groove saved': 'Groove gespeichert',
'not connected': 'nicht verbunden',
'Single Note': 'Einzelne-Note',
'Alternating Notes': 'Alternierende Noten',
'Dual Notes': 'Zwei Noten',
'Groove': 'Groove',
'Bass': 'Bass',
'Sequence error:': 'Sequenzfehler:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'Möglicherweise wurde ein Beat verpasst, möglicherweise aufgrund einer verlorenen Bluetooth-Benachrichtigungsnachricht',
'Bluetooth status': 'Bluetooth-Status.',
'This device does not support Bluetooth': 'Dieses Gerät unterstützt Bluetooth nicht',
'Authorize the HappyFeet app to use Bluetooth and location': 'Autorisieren Sie die HappyFeet-App, um Bluetooth und -ort zu verwenden',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth ist ausgeschaltet. Bitte schalten Sie es ein',
'Enable location services': 'Standortdienste aktivieren',
'Found Happy Feet!  Connecting': 'Glückliche Happy Feet! Anschließen',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': 'Kann keine Happy Feet finden! Besitzt du einen? Ist es in der Nähe? Ist es aufgeladen?',
'Connected!': 'In Verbindung gebracht!',
'Connection failed with with error': 'Verbindung ist mit Fehler fehlgeschlagen',
'Disconnecting': 'Trennen',
'Change language': 'Sprache ändern',
'Firmware revision:': 'Firmware-Revision:',
'Disconnecting since no beats detected for 30 minutes': 'Trennen der Verbindung, da keine Beats für 30 Minuten erkannt werden',
'Audio test mode': 'Audiotest-Modus',
'You cannot use audio test mode if connected.': 'Sie können den Audiotest-Modus nicht verwenden, wenn Sie angeschlossen sind.',
'Audio test mode enabled.': 'Audiotprüfmodus aktiviert.',
'Audio test mode disabled.': 'Audiotest-Modus deaktiviert.',
'In audio test mode, tap the music note button to play the next note.': 'Tippen Sie im Audiot-Testmodus auf die Noten-Note-Taste, um die nächste Note abzuspielen.',
'Loading percussion sounds.': 'Percussion-Sounds laden.',
'Loading bass sounds.': 'Bassgeräusche laden.',
},
'es': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Conectar',
'Disconnect': 'Desconectar',
'MODE': 'MODO',
'Play mode': 'Modo de juego',
'NOTES': 'Notas',
'1st note': '1ª nota',
'2nd note': '2ª nota',
'Happy Feet - Grooves': 'Happy Feet - Surcos',
'DEFINE GROOVE': 'Define la ranura',
'Beats/measure': 'Beats / Medir',
'Measures': 'Medidas',
'Voices': 'Voces',
'1': '1',
'2': '2',
'Backbeat': 'Backbeat',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Elija "-" para no una nota, B para Bass Drum, K for Kick Drum, S para el tambor de la caja, H para HI-HAT CYMBAL, C para Tambourine, C para Cowbell, F para FingersNap, R para la capa de RIM, A para Shaker Shot , W para Woodblock',
'Save groove': 'Guardar ranura',
'Load groove': 'Groove de carga',
'Happy Feet - Bass': 'Pies felices - bajo',
'DEFINE BASS GROOVE': 'Definir Groove Bass',
'Key of': 'Llave de',
'Tones:': 'Tonos:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Elija "-" sin notas, o números romanos i a través de VII PLUS PLANTS para tonos',
'Not set': 'No se establece',
'Happy Feet - Info Menu': 'Happy Feet - menú de información',
'Model number:': 'Número de modelo:',
'Result:': 'Resultado:',
'Error:': 'Error:',
'Awaiting result': 'En espera de resultados',
'Show HappyFeet homepage': 'Mostrar HappyFeet Homepage',
'Happy Feet - Settings Menu': 'Happy Feet - menú de configuración',
'Sensitivity': 'Sensibilidad',
'Less': 'Menos',
'More': 'Más',
'Reset sensitivity to default': 'Restablecer la sensibilidad al valor predeterminado',
'Happy Feet - Save Groove': 'Happy Feet - salvar ranura',
'Enter groove name:': 'Ingrese el nombre de la ranura:',
'Enter a description of the groove:': 'Ingrese una descripción de la ranura:',
'Happy Feet - Load Groove': 'Happy Feet - carga surco',
'Saved grooves:': 'Grooves guardados:',
'Loaded groove': 'Groove cargado',
'Load status': 'Estado de carga',
'Missing or invalid file name:': 'Nombre de archivo faltante o no válido:',
'Notice': 'Aviso',
'Status': 'Estado',
'already connected': 'ya conectado',
'back beat mode can only be used with even number of beats per measure.': 'El modo Back Beat solo se puede usar con un número de latidos aún por medida.',
'beats disabled': 'Beats Discapacitados',
'beats enabled': 'Beats habilitado',
'connect to Bluetooth first': 'Conectar a Bluetooth primero',
'connecting to Bluetooth': 'Conexión a Bluetooth',
'disconnecting Bluetooth': 'Desconexión de Bluetooth',
'groove saved': 'Groove salvado',
'not connected': 'no conectado',
'Single Note': 'Nota individual',
'Alternating Notes': 'Notas alternas',
'Dual Notes': 'Notas duales',
'Groove': 'Groove',
'Bass': 'Bajo',
'Sequence error:': 'Error de secuencia:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'Se extrañó un ritmo, posiblemente debido a un mensaje de notificación de Bluetooth perdida',
'Bluetooth status': 'Estado bluetooth',
'This device does not support Bluetooth': 'Este dispositivo no es compatible con Bluetooth.',
'Authorize the HappyFeet app to use Bluetooth and location': 'Autoriza la aplicación HappyFeet para usar Bluetooth y Ubicación',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth está apagado. Por favor enciéndalo',
'Enable location services': 'Servicio de localización activado',
'Found Happy Feet!  Connecting': '¡Encontrados Happy Feet! Conexión',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': '¡No puedo encontrarHappy Feet! ¿Eres dueño de uno? ¿Está cerca? ¿Está cargado?',
'Connected!': '¡Conectado!',
'Connection failed with with error': 'La conexión falló con el error',
'Disconnecting': 'Desconexión',
'Change language': 'Cambiar idioma',
'Firmware revision:': 'Revisión de firmware:',
'Disconnecting since no beats detected for 30 minutes': 'Desconexión ya que sin latidos detectados durante 30 minutos.',
'Audio test mode': 'Modo de prueba de audio',
'You cannot use audio test mode if connected.': 'No puede usar el modo de prueba de audio si está conectado.',
'Audio test mode enabled.': 'Modo de prueba de audio habilitado.',
'Audio test mode disabled.': 'Modo de prueba de audio deshabilitado.',
'In audio test mode, tap the music note button to play the next note.': 'En el modo de prueba de audio, toque el botón Nota de música para reproducir la siguiente nota.',
'Loading percussion sounds.': 'Cargando sonidos de percusión.',
'Loading bass sounds.': 'Cargando sonidos de bajo.',
},
'it': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Collegare',
'Disconnect': 'Disconnessione',
'MODE': 'MODALITÀ',
'Play mode': 'Modalità di gioco',
'NOTES': 'APPUNTI',
'1st note': '1a nota',
'2nd note': '2 ° Nota',
'Happy Feet - Grooves': 'Happy Feet - Grooves',
'DEFINE GROOVE': 'Definisci Groove.',
'Beats/measure': 'Beats / Measure.',
'Measures': 'Le misure',
'Voices': 'Voices.',
'1': '1.',
'2': '2.',
'Backbeat': 'BackBeat.',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Scegli "-" per nessuna nota, B per Bass Drum, K per Kick Drum, S per il rullante, H per il tamburo Hi-Hat, T per Tambourine, c per il cowbell, f per fingersnap, r per lo scatto, A per shaker , W per woodblock',
'Save groove': 'Salva Groove.',
'Load groove': 'Carica Groove.',
'Happy Feet - Bass': 'Piedi felici - Bass',
'DEFINE BASS GROOVE': 'Definisci la scanalatura dei bassi',
'Key of': 'Chiave di',
'Tones:': 'Toni:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Scegli "-" per nessuna nota, o numeri romani I attraverso VII Plus Appartamenti per i toni',
'Not set': 'Non impostato',
'Happy Feet - Info Menu': 'Happy Feet - menu informazioni',
'Model number:': 'Numero di modello:',
'Result:': 'Risultato:',
'Error:': 'Errore:',
'Awaiting result': 'In attesa di risultati',
'Show HappyFeet homepage': 'Mostra la homepage Happyfeet.',
'Happy Feet - Settings Menu': 'Happy Feet - Menu Impostazioni',
'Sensitivity': 'Sensibilità',
'Less': 'Meno',
'More': 'Di più',
'Reset sensitivity to default': 'Ripristina la sensibilità per impostazione predefinita',
'Happy Feet - Save Groove': 'Happy Feet - Salva Groove',
'Enter groove name:': 'Inserisci il nome Groove:',
'Enter a description of the groove:': 'Inserisci una descrizione della Groove:',
'Happy Feet - Load Groove': 'Happy Feet - Groove di carico',
'Saved grooves:': 'Groove salvate:',
'Loaded groove': 'Groove caricato',
'Load status': 'Lo stato del carico',
'Missing or invalid file name:': 'Nome file mancante o non valido:',
'Notice': 'Avviso',
'Status': 'Stato',
'already connected': 'già connesso',
'back beat mode can only be used with even number of beats per measure.': 'La modalità Beat Back può essere utilizzata solo con il numero pari di Beats per misura.',
'beats disabled': 'Beats Disabili',
'beats enabled': 'Beats abilitato',
'connect to Bluetooth first': 'Connettiti prima al Bluetooth prima',
'connecting to Bluetooth': 'Connessione al Bluetooth',
'disconnecting Bluetooth': 'Disconnessione del Bluetooth',
'groove saved': 'Groove salvato',
'not connected': 'non collegato',
'Single Note': 'Nota singola',
'Alternating Notes': 'Note alternate',
'Dual Notes': 'Dual Notes.',
'Groove': 'Groove',
'Bass': 'Basso',
'Sequence error:': 'Errore di sequenza:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'Un colpo è stato perso, forse a causa di un messaggio Bluetooth perduto informare il messaggio',
'Bluetooth status': 'Stato Bluetooth',
'This device does not support Bluetooth': 'Questo dispositivo non supporta Bluetooth',
'Authorize the HappyFeet app to use Bluetooth and location': 'Autorizza l\'app HappyFeet per utilizzare Bluetooth e posizione',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth è spento. Per favore accendilo',
'Enable location services': 'Abilita i servizi di localizzazione',
'Found Happy Feet!  Connecting': 'Trovato i Happy Feet! Connessione',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': 'Non riesci a trovare Happy Feet! Ne possiedi uno? È vicino? È caricato?',
'Connected!': 'Collegato!',
'Connection failed with with error': 'Connessione non riuscita con l\'errore',
'Disconnecting': 'Disconnessione',
'Change language': 'Cambia lingua',
'Firmware revision:': 'Revisione del firmware:',
'Disconnecting since no beats detected for 30 minutes': 'Disconnessione poiché nessun battito rilevato per 30 minuti',
'Audio test mode': 'Modalità di prova audio',
'You cannot use audio test mode if connected.': 'Non è possibile utilizzare la modalità di test audio se connesso.',
'Audio test mode enabled.': 'Modalità di test audio abilitata.',
'Audio test mode disabled.': 'Modalità di prova audio disabilitata.',
'In audio test mode, tap the music note button to play the next note.': 'Nella modalità Audio Test, tocca il tasto MUSIC Nota per riprodurre la nota successiva.',
'Loading percussion sounds.': 'Caricamento dei suoni percussioni.',
'Loading bass sounds.': 'Caricamento dei suoni dei bassi.',
},
'pt': {
'Happy Feet': 'Happy Feet',
'BLUETOOTH': 'BLUETOOTH',
'Connect': 'Conectar',
'Disconnect': 'desconectar',
'MODE': 'MODO',
'Play mode': 'Modo de reprodução',
'NOTES': 'NOTAS',
'1st note': '1ª Nota',
'2nd note': '2ª nota',
'Happy Feet - Grooves': 'Happy Feet - Grooves',
'DEFINE GROOVE': 'Definir Groove',
'Beats/measure': 'Batidas / medidas',
'Measures': 'Medidas',
'Voices': 'Vozes.',
'1': '1.',
'2': '2.',
'Backbeat': 'Backbeat.',
'Choose "-" for no note, B for bass drum, K for kick drum, S for snare drum, H for hi-hat cymbal, T for tambourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock': 'Escolha "-" para nenhuma nota, B para bateria Bass, K for Kick Drum, S for Snare Drum, H for Hi-Hat Cymbal, T para Tambourina, C para Cowbell, F for Fingersnap, R para Tiro de Rim , W para woodblock',
'Save groove': 'Salvar groove',
'Load groove': 'Groove de carga',
'Happy Feet - Bass': 'Pés felizes - baixo',
'DEFINE BASS GROOVE': 'Definir Groove Bass.',
'Key of': 'Chave de.',
'Tones:': 'TONES:',
'Choose "-" for no note, or Roman numerals I through VII plus flats for tones': 'Escolha "-" sem nota, ou numerais romanos I através de VII Plus Flats para tons',
'Not set': 'Não configurado',
'Happy Feet - Info Menu': 'Happy Feet - Menu Info',
'Model number:': 'Número do modelo:',
'Result:': 'Resultado:',
'Error:': 'Erro:',
'Awaiting result': 'Aguardando resultado',
'Show HappyFeet homepage': 'Mostrar Happyfeet Homepage',
'Happy Feet - Settings Menu': 'Happy Feet - menu de configurações',
'Sensitivity': 'Sensibilidade',
'Less': 'Menos',
'More': 'Mais',
'Reset sensitivity to default': 'Redefinir a sensibilidade para o padrão',
'Happy Feet - Save Groove': 'Happy Feet - salvar groove',
'Enter groove name:': 'Digite o nome do sulco:',
'Enter a description of the groove:': 'Digite uma descrição do Groove:',
'Happy Feet - Load Groove': 'Happy Feet - Grove de carga',
'Saved grooves:': 'Grooves salvas:',
'Loaded groove': 'Groove carregado',
'Load status': 'Status de carga',
'Missing or invalid file name:': 'Nome do arquivo ausente ou inválido:',
'Notice': 'Perceber',
'Status': 'Status',
'already connected': 'já conectado',
'back beat mode can only be used with even number of beats per measure.': 'O modo de beat de volta só pode ser usado com número par de batidas por medida.',
'beats disabled': 'batidas desativadas',
'beats enabled': 'batidas habilitadas',
'connect to Bluetooth first': 'Conecte-se ao Bluetooth primeiro',
'connecting to Bluetooth': 'Conectando-se ao Bluetooth',
'disconnecting Bluetooth': 'Desconectando Bluetooth.',
'groove saved': 'Groove salvo',
'not connected': 'não conectado',
'Single Note': 'Única nota',
'Alternating Notes': 'Notas alternadas',
'Dual Notes': 'Notas duais',
'Groove': 'Groove',
'Bass': 'Baixo',
'Sequence error:': 'Erro de sequência:',
'A beat was missed, possibly due to a lost Bluetooth notify message': 'Uma batida foi perdida, possivelmente devido a uma mensagem de notificação de Bluetooth perdida',
'Bluetooth status': 'Status do Bluetooth.',
'This device does not support Bluetooth': 'Este dispositivo não suporta Bluetooth',
'Authorize the HappyFeet app to use Bluetooth and location': 'Autorize o aplicativo Happyfeet a usar Bluetooth e localização',
'Bluetooth is turned off.  Please turn it on': 'Bluetooth está desligado. Por favor, ligue-o',
'Enable location services': 'Ativar serviços de localização',
'Found Happy Feet!  Connecting': 'Encontrado Happy Feet! Conectando',
'Can\'t find Happy Feet!  Do you own one?  Is it nearby?  Is it charged?': 'Não consigo encontrar Happy Feet! Você possui um? Está nas proximidades? É cobrado?',
'Connected!': 'Conectado!',
'Connection failed with with error': 'Conexão falhou com erro',
'Disconnecting': 'Desconectar',
'Change language': 'Mudar idioma',
'Firmware revision:': 'Revisão de firmware:',
'Disconnecting since no beats detected for 30 minutes': 'Desconectando desde que não há batidas detectadas por 30 minutos',
'Audio test mode': 'Modo de teste de áudio.',
'You cannot use audio test mode if connected.': 'Você não pode usar o modo de teste de áudio se estiver conectado.',
'Audio test mode enabled.': 'Modo de teste de áudio ativado.',
'Audio test mode disabled.': 'Modo de teste de áudio desativado.',
'In audio test mode, tap the music note button to play the next note.': 'No modo de teste de áudio, toque no botão Music Note para reproduzir a próxima nota.',
'Loading percussion sounds.': 'Carregando sons de percussão.',
'Loading bass sounds.': 'Carregando sons graves.',
},
        };
      }
      