import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    '1-tap mode: choose a rhythm, enable beats, tap your foot 4 times as a count-in, and then only on the 1s': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Connect',
'': 'Disconnect',
'': 'MODE',
'': 'Play mode',
'': 'NOTES',
'': '1st note',
'': '2nd note',
'': 'Happy Feet - Grooves',
'': 'DEFINE GROOVE',
'': 'Beats/measure',
'': 'Measures',
'': 'Voices',
'': '1',
'': '2',
'': 'Backbeat',
'': 'Offbeat mode can only be used with even number of beats per measure.',
'': ' Choose "-" for no note, b for bass drum, B for bass echo, t for low tom, T for high tom, S for snare drum, H for hi-hat cymbal, M for taMbourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock, Q for quijada, U for brUshes ',
'': 'Save groove',
'': 'Load groove',
'': 'No saved grooves found.',
'': 'Happy Feet - Bass',
'': 'DEFINE BASS GROOVE',
'': 'Key of',
'': 'Tones:',
'': 'Choose "-" for no note, or numbers 1 through 7 plus flats for tones',
'': 'Not set',
'': 'Happy Feet - Info Menu',
'': 'Model number:',
'': 'Result:',
'': 'Error:',
'': 'Awaiting result',
'': 'Show HappyFeet homepage',
'': 'Happy Feet - Settings Menu',
'': 'Sensitivity',
'': 'Less',
'': 'More',
'': 'You must be connected to adjust.',
'': 'Reset sensitivity to default',
'': 'You must be connected to reset to default.',
'': 'Happy Feet - Save Groove',
'': 'Enter groove name:',
'': 'Enter a description of the groove:',
'': 'Happy Feet - Load Groove',
'': 'Saved grooves:',
'': 'Loaded groove',
'': 'Load status',
'': 'Missing or invalid file name:',
'': 'Notice',
'': 'Status',
'': 'already connected',
'': 'back beat mode can only be used with even number of beats per measure.',
'': 'beats disabled',
'': 'beats enabled',
'': 'connect to Bluetooth first',
'': 'connecting to Bluetooth',
'': 'disconnecting Bluetooth',
'': 'groove saved',
'': 'not connected',
'': 'Single Note',
'': 'Alternating Notes',
'': 'Dual Notes',
'': 'Groove',
'': 'Bass',
'': 'Sequence error:',
'': 'A beat was missed, possibly due to a lost Bluetooth notify message',
'': 'Bluetooth status',
'': 'This device does not support Bluetooth',
'': 'Authorize the HappyFeet app to use Bluetooth and location',
'': 'Bluetooth is turned off.  Please turn it on',
'': 'Enable location services',
'': 'Found Happy Feet!  Connecting',
'': 'No HappyFeet found!  Do you own one?  Is it nearby?  Is it charged?',
'': 'Connected!',
'': 'Connection failed with with error',
'': 'Disconnecting',
'': 'Change language',
'': 'Firmware revision:',
'': 'Disconnecting since no beats detected for 30 minutes',
'': 'Audio test mode',
'': 'You cannot use audio test mode if connected.',
'': 'Audio test mode enabled.',
'': 'Audio test mode disabled.',
'': 'In audio test mode, tap the music note button to play the next note.',
'': 'Loading percussion sounds.',
'': 'Loading bass sounds.',
'': '1-tap mode: choose a rhythm, enable beats, tap your foot 4 times as a count-in, and then only on the 1s',
'': '1-tap mode: choose a rhythm, enable beats, tap your foot 4 times as a count-in, and then only on the first 1',
'': 'Tablature',
'': 'Tablature is a simplified form of music notation. See www.drumtabs.org for more details.',
'': 'Lead-in count:',
'': 'HappyFeet - 1-tap Menu',
'': 'Rhythm',
'': '1-tap rhythm: rock1',
'': '1-tap rhythm: rock2',
'': '1-tap rhythm: jazz1',
'': '1-tap rhythm: Bossa Nova',
'': '1-tap rhythm: merengue',
'': '1-tap rhythm: Afro-Cuban 6/8',
'': '1-tap rhythm: samba',
'': '1-tap rhythm: salsa',
'': 'Serial number:',
'': 'Multi mode',
'': 'Multi mode enabled.',
'': 'Multi mode disabled.',
'': 'Use multi mode if you have more than one HappyFeet.',
'': 'HappyFeet - Multi-connect',
'': 'Select an available HappyFeet:',
'': 'Nearby HappyFeet are listed from closest to furthest as shown by RSSI',
'': 'Battery charge level:',
'': 'Foot enable/disable received',
'': 'Practice',
'': 'Happy Feet - Practice Menu',
'': 'Sound',
'': 'Tempo [BPM]',
'': 'Beats enabled by foot',
'': 'Beats disabled by foot',
'': 'Choose a sound, set the tempo, enable beats and tap your foot.',
'': 'Measured tempo:',
'': 'Streak count:',
'': 'Number of successive beats that are close to the target tempo.',
'': 'Foot switch',
'': 'Foot switch enabled.',
'': 'Foot switch disabled.',
'': 'When the foot switch is enabled, you can enable or disable beats by moving your foot quickly to either side while flat on the floor.',
'': 'BPM should be 180 or less.',
'': 'BPM should be 40 or more.',
'': 'In offbeat mode, sounds are played between beats. Beats are shown in blue and offbeats in purple.',
'': 'Angle',
'': 'Metronome',
'': 'When enabled, a tone will be played at the selected tempo.',
'': 'Show privacy policy',
'': 'Auto mode',
'': 'Auto mode enabled.',
'': 'Auto mode disabled.',
'': 'When auto mode is enabled, in 1-tap mode you only have to tap you foot on the first 1, and the groove plays automatically.',
},
'en': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Connect',
'': 'Disconnect',
'': 'MODE',
'': 'Play mode',
'': 'NOTES',
'': '1st note',
'': '2nd note',
'': 'Happy Feet - Grooves',
'': 'DEFINE GROOVE',
'': 'Beats/measure',
'': 'Measures',
'': 'Voices',
'': '1',
'': '2',
'': 'Backbeat',
'': 'Offbeat mode can only be used with even number of beats per measure.',
'': ' Choose "-" for no note, b for bass drum, B for bass echo, t for low tom, T for high tom, S for snare drum, H for hi-hat cymbal, M for taMbourine, C for cowbell, F for fingersnap, R for rim shot, A for shAker, W for woodblock, Q for quijada, U for brUshes ',
'': 'Save groove',
'': 'Load groove',
'': 'No saved grooves found.',
'': 'Happy Feet - Bass',
'': 'DEFINE BASS GROOVE',
'': 'Key of',
'': 'Tones:',
'': 'Choose "-" for no note, or numbers 1 through 7 plus flats for tones',
'': 'Not set',
'': 'Happy Feet - Info Menu',
'': 'Model number:',
'': 'Result:',
'': 'Error:',
'': 'Awaiting result',
'': 'Show HappyFeet homepage',
'': 'Happy Feet - Settings Menu',
'': 'Sensitivity',
'': 'Less',
'': 'More',
'': 'You must be connected to adjust.',
'': 'Reset sensitivity to default',
'': 'You must be connected to reset to default.',
'': 'Happy Feet - Save Groove',
'': 'Enter groove name:',
'': 'Enter a description of the groove:',
'': 'Happy Feet - Load Groove',
'': 'Saved grooves:',
'': 'Loaded groove',
'': 'Load status',
'': 'Missing or invalid file name:',
'': 'Notice',
'': 'Status',
'': 'already connected',
'': 'back beat mode can only be used with even number of beats per measure.',
'': 'beats disabled',
'': 'beats enabled',
'': 'connect to Bluetooth first',
'': 'connecting to Bluetooth',
'': 'disconnecting Bluetooth',
'': 'groove saved',
'': 'not connected',
'': 'Single Note',
'': 'Alternating Notes',
'': 'Dual Notes',
'': 'Groove',
'': 'Bass',
'': 'Sequence error:',
'': 'A beat was missed, possibly due to a lost Bluetooth notify message',
'': 'Bluetooth status',
'': 'This device does not support Bluetooth',
'': 'Authorize the HappyFeet app to use Bluetooth and location',
'': 'Bluetooth is turned off.  Please turn it on',
'': 'Enable location services',
'': 'Found Happy Feet!  Connecting',
'': 'No HappyFeet found!  Do you own one?  Is it nearby?  Is it charged?',
'': 'Connected!',
'': 'Connection failed with with error',
'': 'Disconnecting',
'': 'Change language',
'': 'Firmware revision:',
'': 'Disconnecting since no beats detected for 30 minutes',
'': 'Audio test mode',
'': 'You cannot use audio test mode if connected.',
'': 'Audio test mode enabled.',
'': 'Audio test mode disabled.',
'': 'In audio test mode, tap the music note button to play the next note.',
'': 'Loading percussion sounds.',
'': 'Loading bass sounds.',
'': '1-tap mode: choose a rhythm, enable beats, tap your foot 4 times as a count-in, and then only on the 1s',
'': '1-tap mode: choose a rhythm, enable beats, tap your foot 4 times as a count-in, and then only on the first 1',
'': 'Tablature',
'': 'Tablature is a simplified form of music notation. See www.drumtabs.org for more details.',
'': 'Lead-in count:',
'': 'HappyFeet - 1-tap Menu',
'': 'Rhythm',
'': '1-tap rhythm: rock1',
'': '1-tap rhythm: rock2',
'': '1-tap rhythm: jazz1',
'': '1-tap rhythm: Bossa Nova',
'': '1-tap rhythm: merengue',
'': '1-tap rhythm: Afro-Cuban 6/8',
'': '1-tap rhythm: samba',
'': '1-tap rhythm: salsa',
'': 'Serial number:',
'': 'Multi mode',
'': 'Multi mode enabled.',
'': 'Multi mode disabled.',
'': 'Use multi mode if you have more than one HappyFeet.',
'': 'HappyFeet - Multi-connect',
'': 'Select an available HappyFeet:',
'': 'Nearby HappyFeet are listed from closest to furthest as shown by RSSI',
'': 'Battery charge level:',
'': 'Foot enable/disable received',
'': 'Practice',
'': 'Happy Feet - Practice Menu',
'': 'Sound',
'': 'Tempo [BPM]',
'': 'Beats enabled by foot',
'': 'Beats disabled by foot',
'': 'Choose a sound, set the tempo, enable beats and tap your foot.',
'': 'Measured tempo:',
'': 'Streak count:',
'': 'Number of successive beats that are close to the target tempo.',
'': 'Foot switch',
'': 'Foot switch enabled.',
'': 'Foot switch disabled.',
'': 'When the foot switch is enabled, you can enable or disable beats by moving your foot quickly to either side while flat on the floor.',
'': 'BPM should be 180 or less.',
'': 'BPM should be 40 or more.',
'': 'In offbeat mode, sounds are played between beats. Beats are shown in blue and offbeats in purple.',
'': 'Angle',
'': 'Metronome',
'': 'When enabled, a tone will be played at the selected tempo.',
'': 'Show privacy policy',
'': 'Auto mode',
'': 'Auto mode enabled.',
'': 'Auto mode disabled.',
'': 'When auto mode is enabled, in 1-tap mode you only have to tap you foot on the first 1, and the groove plays automatically.',
},
'fr': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Connecter',
'': 'Débrancher',
'': 'MODE',
'': 'Mode de jeu',
'': 'REMARQUES',
'': '1ère note',
'': '2e note',
'': 'Happy Feet - Grooves',
'': 'Définir le groove',
'': 'Bat / mesure',
'': 'Mesures',
'': 'Voix',
'': '1',
'': '2',
'': 'Backbeat',
'': 'Le mode décalé ne peut être utilisé qu\'avec un nombre uniforme de battements par mesure.',
'': ' Choisissez "-" pour aucune note, B pour le tambour de basse, B pour l\'écho de basse, t pour tom bas, t pour high tom, s pour la caisse claire, h pour cymbale hi-hat, m pour tambourine, c pour barbe à vache, f pour doigtsnap, r pour jante shot, un pour shaker, w for woodblock, q pour Quijada, u pour les pinceaux',
'': 'Sauvegarder le groove',
'': 'Charger un groove',
'': 'Pas de grooves sauvegardées trouvées.',
'': 'Happy Feet - Basse',
'': 'Définir le groove de basse',
'': 'Clé de',
'': 'Tons:',
'': 'Choisissez "-" pour aucune note, ou les numéros 1 à 7 plus des appartements pour les tons',
'': 'Pas encore défini',
'': 'Happy Feet - Menu Info',
'': 'Numéro de modèle:',
'': 'Résultat:',
'': 'Erreur:',
'': 'En attente de résultat',
'': 'Montrer la page d\'accueil de Happy Feet',
'': 'Happy Feet - Menu Paramètres',
'': 'Sensibilité',
'': 'Moins',
'': 'Suite',
'': 'Vous devez être connecté pour régler.',
'': 'Réinitialiser la sensibilité à la valeur par défaut',
'': 'Vous devez être connecté à la réinitialisation par défaut.',
'': 'Happy Feet - sauvegarder le groove',
'': 'Entrez le nom du groove:',
'': 'Entrez une description du groove:',
'': 'Happy Feet - Charger un groove',
'': 'Grooves sauvegardés:',
'': 'Groove chargé',
'': 'Statut de chargement',
'': 'Nom de fichier manquant ou non valide:',
'': 'Remarquer',
'': 'Statut',
'': 'Déjà connecté',
'': 'Le mode "Back Beat" ne peut être utilisé qu\'avec un nombre pair de battements par mesure.',
'': 'bat handicapé',
'': 'Les battements activés',
'': 'Connectez-vous d\'abord à Bluetooth',
'': 'Connexion à Bluetooth',
'': 'déconnecter le Bluetooth',
'': 'groove sauvé',
'': 'pas connecté',
'': 'Note unique',
'': 'Notes en alternance',
'': 'Doubles notes',
'': 'Groove',
'': 'Basse',
'': 'Erreur de séquence:',
'': 'Un battement a été manqué, peut-être en raison d\'un message Bluetooth perdu',
'': 'Statut Bluetooth',
'': 'Cet appareil ne prend pas en charge Bluetooth',
'': 'Autoriser l\'application HappyFeet à utiliser Bluetooth et l\'emplacement',
'': 'Bluetooth est éteint. Veuillez l\'allumer',
'': 'Activer les services de localisation',
'': 'Trouvé Happy Feet! De liaison',
'': 'Vous ne pouvez pas trouver des Happy Feet! Êtes-vous le propriétaire? Est-ce à proximité? Est-ce chargé?',
'': 'Lié!',
'': 'La connexion a échoué avec l\'erreur',
'': 'Déconnecter',
'': 'Changer de langue',
'': 'Révision du micrologiciel:',
'': 'Déconnecter car aucun battement n\'a été détecté pendant 30 minutes',
'': 'Mode de test audio',
'': 'Vous ne pouvez pas utiliser le mode de test audio s\'il est connecté.',
'': 'Mode de test audio activé.',
'': 'Mode de test audio désactivé.',
'': 'En mode test audio, appuyez sur le bouton Music Note pour lire la note suivante.',
'': 'Chargement des sons de percussion.',
'': 'Chargement des sons de basse.',
'': 'Mode 1-Tap: choisissez un rythme, activez les battements, appuyez sur votre pied 4 fois comme compte, puis uniquement sur les 1',
'': 'Mode 1-Tap: choisissez un rythme, activez les battements, appuyez sur votre pied 4 fois comme compte, puis uniquement sur le premier 1',
'': 'Tablature',
'': 'La tablature est une forme simplifiée de notation musicale. Voir www.drumtabs.org pour plus de détails.',
'': 'Compte d\'entrée:',
'': 'Happyfeet - Menu 1-Tap',
'': 'Rythme',
'': 'Rythme 1-Tap: ROCK1',
'': 'Rythme 1-Tap: ROCK2',
'': 'Rythme 1-Tap: Jazz1',
'': 'Rythme 1-Tap: Bossa Nova',
'': 'Rythme 1-Tap: Merengue',
'': 'Rythme 1-Tap: Afro-Cuban 6/8',
'': 'Rythme 1-Tap: Samba',
'': 'Rythme 1-Tap: Salsa',
'': 'Numéro de série:',
'': 'Mode multiple',
'': 'MOTI-MODE activé.',
'': 'MODE MOTTIFICATIVE.',
'': 'Utilisez Multi Mode si vous avez plus d\'un HAYEFEET.',
'': 'Happyfeet - multi-connexion',
'': 'Sélectionnez une feuille de HappyFeet disponible:',
'': 'Happyfeet à proximité est répertorié du plus proche au plus éloigné comme le montre RSSI',
'': 'Niveau de charge de la batterie:',
'': 'Activer / désactiver le pied reçu',
'': 'Pratique',
'': 'Happy Feet - Menu d\'entraînement',
'': 'Du son',
'': 'Tempo [bpm]',
'': 'Beats activés au pied',
'': 'Beats handicapés au pied',
'': 'Choisissez un son, définissez le tempo, activez les battements et appuyez sur votre pied.',
'': 'Tempo mesuré:',
'': 'Count de séquences:',
'': 'Nombre de battements successifs qui sont proches du tempo cible.',
'': 'Interrupteur au pied',
'': 'Interrupteur de pied activé.',
'': 'Interrupteur de pied désactivé.',
'': 'Lorsque l\'interrupteur à pied est activé, vous pouvez activer ou désactiver les battements en déplaçant votre pied rapidement de chaque côté tout en étant plat sur le sol.',
'': 'BPM devrait être 180 ou moins.',
'': 'BPM doit être 40 ou plus.',
'': 'En mode décalé, les sons sont joués entre les battements. Les battements sont représentés en bleu et décalés en violet.',
'': 'Angle',
'': 'Métronome',
'': 'Lorsqu\'il est activé, un ton sera joué au tempo sélectionné.',
'': 'Afficher la politique de confidentialité',
'': 'Mode automatique',
'': 'Mode automatique activé.',
'': 'Mode automatique désactivé.',
'': 'Lorsque le mode automatique est activé, en mode 1-TAP, vous n\'avez qu\'à appuyer sur votre pied sur le premier 1, et le groove joue automatiquement.',
},
'de': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Verbinden',
'': 'Trennen',
'': 'MODUS',
'': 'Spiel-Modus',
'': 'ANMERKUNGEN',
'': '1. Note',
'': '2. Note',
'': 'Happy Feet - Grooves',
'': 'Groove definieren',
'': 'Beats / Takt',
'': 'Takt',
'': 'Voices.',
'': '1',
'': '2',
'': 'Backbeat',
'': 'Der Offbeat -Modus kann nur mit einer Anzahl von Schlägen pro Maß verwendet werden.',
'': 'Wählen Sie "-" für keine Note, B für Bassdrum, K für Kick Drum, S für Snare Drum, H für Hi-Hat-Becken, T für Tamburin, C für Cowbell, F für Fingersnap, R für Rim-Schuss, A für Shaker , W für Woodblock',
'': 'Groove speichern',
'': 'Groove laden',
'': 'Keine gespeicherten Rillen gefunden.',
'': 'Happy Feet - Bass',
'': 'Bass Groove definieren',
'': 'Schlüssel von',
'': 'Töne:',
'': 'Wählen Sie "-" ohne Hinweis oder Nummern 1 bis 7 plus Wohnungen für Töne',
'': 'Nicht eingestellt',
'': 'Happy Feet - Info-Menü',
'': 'Modell-Nr:',
'': 'Ergebnis:',
'': 'Fehler:',
'': 'Warten auf das Ergebnis',
'': 'HappyFeet-Homepage anzeigen.',
'': 'Happy Feet - Einstellungen Menü',
'': 'Erkennungsschwelle',
'': 'Weniger',
'': 'Mehr',
'': 'Sie müssen angeschlossen sein, um sich anzupassen.',
'': 'Setzen Sie die Empfindlichkeit gegenüber Standard zurück',
'': 'Sie müssen mit dem Zurücksetzen an Standard angeschlossen sein.',
'': 'Happy Feet - Groove speichern',
'': 'Groovename eingeben:',
'': 'Geben Sie eine Beschreibung der Groove ein:',
'': 'Happy Feet - Groove laden',
'': 'Gespeicherte Grooves:',
'': 'Geladene Grovves',
'': 'Status laden',
'': 'Fehlender oder ungültiger Dateiname:',
'': 'Notiz',
'': 'Status',
'': 'schon verbunden',
'': 'Der Back-Beat-Modus kann nur mit geraden Anzahl von Beats pro Takt verwendet werden.',
'': 'Beats ausgeschaltet',
'': 'Beats aktiviert',
'': 'Verbinden Sie sich zuerst mit Bluetooth',
'': 'Verbindung zu Bluetooth',
'': 'Bluetooth trennen',
'': 'Groove gespeichert',
'': 'nicht verbunden',
'': 'Einzelne-Note',
'': 'Alternierende Noten',
'': 'Zwei Noten',
'': 'Groove',
'': 'Bass',
'': 'Sequenzfehler:',
'': 'Ein Beat wurde verpasst, möglicherweise aufgrund einer verlorenen Bluetooth -Benachrichtigungsnachricht',
'': 'Bluetooth -Status',
'': 'Dieses Gerät unterstützt Bluetooth nicht',
'': 'Genehmigen Sie die Happyfeet -App, um Bluetooth und Standort zu verwenden',
'': 'Bluetooth wird ausgeschaltet. Bitte schalten Sie es ein',
'': 'Standortdienste aktivieren',
'': 'Glückliche Happy Feet! Anschließen',
'': 'Kann keine Happy Feet finden! Besitzt du einen? Ist es in der Nähe? Ist es aufgeladen?',
'': 'In Verbindung gebracht!',
'': 'Die Verbindung ist mit Fehler fehlgeschlagen',
'': 'Trennen',
'': 'Sprache ändern',
'': 'Firmware Revision:',
'': 'Trennen, da keine Beats 30 Minuten erkannt wurden',
'': 'Audio -Testmodus',
'': 'Sie können den Audio -Testmodus nicht verwenden, wenn Sie angeschlossen sind.',
'': 'Audio -Testmodus aktiviert.',
'': 'Audio -Testmodus deaktiviert.',
'': 'Tippen Sie im Audio -Testmodus auf die Schaltfläche Music Note, um die nächste Note abzuspielen.',
'': 'Laden von Percussion -Geräuschen.',
'': 'Bassklänge laden.',
'': '1-Tap-Modus: Wählen Sie einen Rhythmus, Aktivieren Sie Beats, tippen Sie 4 Mal als Count-In und dann nur auf den 1s',
'': '1-Tap-Modus: Wählen Sie einen Rhythmus, Aktivieren Sie Beats, tippen Sie 4 Mal als Count-In und dann nur bei den ersten 1',
'': 'Tablatur',
'': 'Tabulatur ist eine vereinfachte Form der Musiknotation. Weitere Informationen finden Sie unter www.drumtabs.org.',
'': 'LEAD-IN-Zählung:',
'': 'Happyfeet - 1 -Tap -Menü',
'': 'Rhythmus',
'': '1-Tap-Rhythmus: Rock1',
'': '1-Tap-Rhythmus: Rock2',
'': '1-Tap-Rhythmus: Jazz1',
'': '1-Tap-Rhythmus: Bossa Nova',
'': '1-Tap-Rhythmus: Merengue',
'': '1-Tap-Rhythmus: Afro-Cuban 6/8',
'': '1-Tap-Rhythmus: Samba',
'': '1-Tap-Rhythmus: Salsa',
'': 'Seriennummer:',
'': 'Multi -Modus',
'': 'Multi -Modus aktiviert.',
'': 'Multi -Modus deaktiviert.',
'': 'Verwenden Sie einen Multi -Modus, wenn Sie mehr als einen HappyFeet haben.',
'': 'Happyfeet - Multi -Connect',
'': 'Wählen Sie einen verfügbaren Happyfeet aus:',
'': 'In der Nähe von HappyFeet sind von RSSI am nächsten zu am weitesten gelistet',
'': 'Batterieladeladung:',
'': 'Fuß aktivieren/deaktivieren empfangen',
'': 'Trainieren',
'': 'Happy Feet - Übungsmenü üben',
'': 'Klang',
'': 'Tempo [BPM]',
'': 'Beats zum Fuß aktiviert',
'': 'Schlägt zum Fuß deaktiviert',
'': 'Wählen Sie einen Sound, stellen Sie das Tempo ein, aktivieren Sie Beats und tippen Sie auf Ihren Fuß.',
'': 'Gemessenes Tempo:',
'': 'Streifenzahl:',
'': 'Anzahl der aufeinanderfolgenden Beats, die dem Zieltempo nahe stehen.',
'': 'Fußschalter',
'': 'Fußschalter aktiviert.',
'': 'Fußschalter deaktiviert.',
'': 'Wenn der Fußschalter aktiviert ist, können Sie Beats aktivieren oder deaktivieren, indem Sie Ihren Fuß schnell auf beide Seiten bewegen, während Sie flach auf dem Boden sind.',
'': 'BPM sollte 180 oder weniger sein.',
'': 'BPM sollte 40 oder mehr sein.',
'': 'Im ungewöhnlichen Modus werden Geräusche zwischen Beats gespielt. Beats sind in Blau und unpolitsch ausgebildet.',
'': 'Winkel',
'': 'Metronom',
'': 'Wenn es aktiviert ist, wird im ausgewählten Tempo ein Ton gespielt.',
'': 'Datenschutzrichtlinie zeigen',
'': 'Automatikmodus',
'': 'Auto -Modus aktiviert.',
'': 'Auto -Modus deaktiviert.',
'': 'Wenn der Auto-Modus aktiviert ist, müssen Sie im 1-Tap-Modus nur auf den Fuß auf den ersten 1 tippen, und der Rille wird automatisch abgespielt.',
},
'es': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Conectar',
'': 'Desconectar',
'': 'MODO',
'': 'Modo de juego',
'': 'Notas',
'': 'Primera nota',
'': 'Segunda nota',
'': 'Happy Feet - Surcos',
'': 'Definir el surco',
'': 'Ritmos/medida',
'': 'Medidas',
'': 'Voces',
'': '1',
'': '2',
'': 'Brote',
'': 'El modo fuera de lo común solo se puede usar con un número par de latidos por medida.',
'': ' Elija "-" Sin nota, B para el bombo, B para el eco de bajo, T para Tom Low Tom, T para Tom Alto, S para Drum Snare, H para Cymbal de Hi-Hat, M para Tambourina, C para Cowbell, F para Fingersnap, R para Rim Shot, A For Shaker, W para Woodblock, Q para Quijada, u para cepillos',
'': 'Guardar el ritmo',
'': 'Ranura de carga',
'': 'No se encontraron surcos guardados.',
'': 'Feest Feet - Bass',
'': 'Definir el ritmo de bajo',
'': 'Llave de',
'': 'Tonos:',
'': 'Elija "-" sin nota, o números 1 a 7 más pisos para tonos',
'': 'No establecido',
'': 'Happy Feet - menú de información',
'': 'Número de modelo:',
'': 'Resultado:',
'': 'Error:',
'': 'Resultado en espera',
'': 'Mostrar página de inicio de HappyFeet',
'': 'Happy Feet - menú de configuración',
'': 'Sensibilidad',
'': 'Menos',
'': 'Más',
'': 'Debes estar conectado para ajustarte.',
'': 'Restablecer la sensibilidad al valor predeterminado',
'': 'Debe estar conectado a restablecer al valor predeterminado.',
'': 'Happy Feet - salvar ranura',
'': 'Ingrese el nombre del ritmo:',
'': 'Ingrese una descripción del surco:',
'': 'Happy Feet - carga surco',
'': 'Surcos guardados:',
'': 'Ranura cargada',
'': 'Estado de carga',
'': 'Nombre de archivo faltante o no válido:',
'': 'Aviso',
'': 'Estado',
'': 'ya conectado',
'': 'El modo Back Beat solo se puede usar con un número par de latidos por medida.',
'': 'Beats discapacitado',
'': 'ritmos habilitados',
'': 'Conéctese a Bluetooth primero',
'': 'conectarse a Bluetooth',
'': 'desconectando Bluetooth',
'': 'Groove guardado',
'': 'no conectado',
'': 'Nota única',
'': 'Notas alternativas',
'': 'Notas duales',
'': 'Groove',
'': 'Bajo',
'': 'Error de secuencia:',
'': 'Se perdió un ritmo, posiblemente debido a un mensaje de notificación de Bluetooth perdido',
'': 'Estado de Bluetooth',
'': 'Este dispositivo no admite Bluetooth',
'': 'Autorice la aplicación HappyFeet para usar Bluetooth y ubicación',
'': 'Bluetooth está apagado. Por favor enciéndalo',
'': 'Servicio de localización activado',
'': '¡Encontrados Happy Feet! Conexión',
'': '¡No puedo encontrarHappy Feet! ¿Eres dueño de uno? ¿Está cerca? ¿Está cargado?',
'': '¡Conectado!',
'': 'La conexión falló con el error',
'': 'Desconexión',
'': 'Cambiar idioma',
'': 'Revisión de firmware:',
'': 'Desconectando ya que no hay ritmos detectados durante 30 minutos',
'': 'Modo de prueba de audio',
'': 'No puede usar el modo de prueba de audio si está conectado.',
'': 'Modo de prueba de audio habilitado.',
'': 'Modo de prueba de audio deshabilitado.',
'': 'En el modo de prueba de audio, toque el botón Nota de música para reproducir la siguiente nota.',
'': 'Sonidos de percusión de carga.',
'': 'Cargando sonidos de graves.',
'': 'Modo de 1 tap: elija un ritmo, habilite los ritmos, toque el pie 4 veces como un conteo, y luego solo en el 1S',
'': 'Modo de 1 tapón: elija un ritmo, habilite los ritmos, toque el pie 4 veces como un conteo, y luego solo en el primer 1',
'': 'Tablatura',
'': 'La tablatura es una forma simplificada de notación musical. Consulte www.drumtabs.org para más detalles.',
'': 'Conteo de plomo:',
'': 'HappyFeet - Menú de 1 tope',
'': 'Ritmo',
'': 'Ritmo de 1 tap: Rock1',
'': 'Ritmo de 1 tap: Rock2',
'': 'Ritmo de 1-tap: jazz1',
'': 'Ritmo de 1-tap: bossa nova',
'': 'Ritmo de 1-tap: merengue',
'': 'Ritmo de 1 tap: afrocuban 6/8',
'': 'Ritmo de 1 tap: samba',
'': 'Ritmo de 1 tap: salsa',
'': 'Número de serie:',
'': 'Modo múltiple',
'': 'Modo múltiple habilitado.',
'': 'Modo múltiple deshabilitado.',
'': 'Use el modo múltiple si tiene más de un happyfeet.',
'': 'HappyFeet - múltiple conecta',
'': 'Seleccione un HappyFeet disponible:',
'': 'La cercana Happyfeet se enumeran de más cercano a más lejos como se muestra por RSSI',
'': 'Nivel de carga de la batería:',
'': 'Pie Enable/deshabilitar recibido',
'': 'Práctica',
'': 'Feest Feet - Menú de práctica',
'': 'Sonido',
'': 'Tempo [BPM]',
'': 'Ritmos habilitados por pie',
'': 'Beats discapacitados por pie',
'': 'Elija un sonido, configure el tempo, habilite los ritmos y toque su pie.',
'': 'Tempo medido:',
'': 'Cuenta de rayas:',
'': 'Número de ritmos sucesivos que están cerca del tempo objetivo.',
'': 'Interruptor de pie',
'': 'Interruptor de pie habilitado.',
'': 'Interruptor de pie deshabilitado.',
'': 'Cuando el interruptor de pie está habilitado, puede habilitar o deshabilitar los ritmos moviendo el pie rápidamente a cada lado mientras está plano en el piso.',
'': 'BPM debe ser 180 o menos.',
'': 'BPM debe ser de 40 o más.',
'': 'En modo fuera de lo común, los sonidos se reproducen entre ritmos. Los ritmos se muestran en azul y criminal en púrpura.',
'': 'Ángulo',
'': 'Metrónomo',
'': 'Cuando se habilita, se reproducirá un tono en el tempo seleccionado.',
'': 'Mostrar política de privacidad',
'': 'Modo automático',
'': 'Modo automático habilitado.',
'': 'Modo automático deshabilitado.',
'': 'Cuando el modo automático está habilitado, en modo de 1 t-tap, solo tiene que tocar su pie en el primer 1, y el surco se reproduce automáticamente.',
},
'it': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Collegare',
'': 'Disconnessione',
'': 'MODALITÀ',
'': 'Modalità di gioco',
'': 'APPUNTI',
'': '1a nota',
'': '2a nota',
'': 'Happy Feet - Grooves',
'': 'Definire il groove',
'': 'Battiti/misura',
'': 'Le misure',
'': 'Voci',
'': '1',
'': '2',
'': 'Backbeat',
'': 'La modalità insolita può essere utilizzata solo con un numero pari di battiti per misura.',
'': ' Scegli "-" per nessuna nota, b per bass tamburo, b per eco di bassi, t per bassa tom, t per tom alto, s per rullante, h per il piatto hi-hat, m per tamburino, c per campanaccio, f per Fingersnap, r per il tiro a bordo, a per shaker, w per bosco, q per Quijada, u per pennelli',
'': 'Salva groove',
'': 'Carica scanalatura',
'': 'Nessuna scaletta salvata trovata.',
'': 'Feet Happy Feet - Bass',
'': 'Definire il ritmo di basso',
'': 'Chiave di',
'': 'Toni:',
'': 'Scegli "-" per nessuna nota o numeri da 1 a 7 più appartamenti per toni',
'': 'Non impostato',
'': 'Happy Feet - menu informazioni',
'': 'Numero di modello:',
'': 'Risultato:',
'': 'Errore:',
'': 'In attesa di risultato',
'': 'Mostra homepage di Happyfeet',
'': 'Happy Feet - Menu Impostazioni',
'': 'Sensibilità',
'': 'Meno',
'': 'Di più',
'': 'Devi essere collegato per regolare.',
'': 'Ripristina la sensibilità al valore predefinito',
'': 'È necessario essere collegati per ripristinare il valore predefinito.',
'': 'Happy Feet - Salva Groove',
'': 'Immettere il nome di groove:',
'': 'Immettere una descrizione del solco:',
'': 'Happy Feet - Groove di carico',
'': 'Scanalature salvate:',
'': 'Scanalatura caricata',
'': 'Stato di carico',
'': 'Nome file mancante o non valido:',
'': 'Avviso',
'': 'Stato',
'': 'già connesso',
'': 'La modalità back beat può essere utilizzata solo con un numero pari di battiti per misura.',
'': 'batti disabili',
'': 'battiti abilitati',
'': 'Connettiti prima a Bluetooth',
'': 'Connessione a Bluetooth',
'': 'Scollegare il Bluetooth',
'': 'Groove salvato',
'': 'non collegata',
'': 'Nota singola',
'': 'Note alternate',
'': 'Dual Note',
'': 'Groove',
'': 'Basso',
'': 'Errore di sequenza:',
'': 'È stato mancato un battito, probabilmente a causa di un messaggio di notifica Bluetooth perduto',
'': 'Stato bluetooth',
'': 'Questo dispositivo non supporta Bluetooth',
'': 'Autorizza l\'app Happyfeet a utilizzare Bluetooth e posizione',
'': 'Il Bluetooth è spento. Si prega di accenderlo',
'': 'Abilita i servizi di localizzazione',
'': 'Trovato i Happy Feet! Connessione',
'': 'Non riesci a trovare Happy Feet! Ne possiedi uno? È vicino? È caricato?',
'': 'Collegato!',
'': 'Connessione non riuscita con l\'errore',
'': 'Disconnessione',
'': 'Cambia lingua',
'': 'Revisione del firmware:',
'': 'Scollegare poiché non sono stati rilevati battiti per 30 minuti',
'': 'Modalità test audio',
'': 'Non è possibile utilizzare la modalità di test audio se collegato.',
'': 'Modalità test audio abilitata.',
'': 'Modalità test audio disabilitato.',
'': 'In modalità test audio, tocca il pulsante NOTA MUSICA per riprodurre la nota successiva.',
'': 'Caricamento dei suoni di percussioni.',
'': 'Caricamento dei suoni dei bassi.',
'': 'Modalità 1-TAP: scegli un ritmo, abilita battiti, tocca il piede 4 volte come conteggio e quindi solo su 1s',
'': 'Modalità 1-TAP: scegli un ritmo, abilita battiti, tocca il piede 4 volte come conteggio e poi solo sul primo 1',
'': 'Tablatura',
'': 'La tablatura è una forma semplificata di notazione musicale. Vedi www.drumtabs.org per maggiori dettagli.',
'': 'Conteggio di lead-in:',
'': 'Happyfeet - menu a 1 tap',
'': 'Ritmo',
'': 'Rhythm da 1 tAP: Rock1',
'': 'Rhythm 1-tAP: Rock2',
'': 'Rhythm da 1 tAP: jazz1',
'': 'Rhythm da 1 tAP: Bossa Nova',
'': 'Rhythm da 1 tAP: Merengue',
'': 'Rhythm da 1-tap: Afro-Cuban 6/8',
'': 'Rhythm da 1 top: samba',
'': 'Rhythm da 1 tAP: salsa',
'': 'Numero di serie:',
'': 'Modalità multi',
'': 'Modalità multi -abilitata.',
'': 'Modalità multipla disabilitata.',
'': 'Usa la modalità Multi se hai più di un Happyfeet.',
'': 'Happyfeet - multi -connessione',
'': 'Seleziona un Happyfeet disponibile:',
'': 'Happyfeet nelle vicinanze sono elencati dal più vicino al più lontano come mostrato da RSSI',
'': 'Livello di carica della batteria:',
'': 'Abilita/disabilita del piede ricevuto',
'': 'Pratica',
'': 'Feet Happy - Pratica menu',
'': 'Suono',
'': 'Tempo [BPM]',
'': 'Battiti abilitati a piedi',
'': 'Beats disabilitati a piedi',
'': 'Scegli un suono, imposta il tempo, abilita battiti e tocca il piede.',
'': 'Tempo misurato:',
'': 'Conteggio delle strisce:',
'': 'Numero di battiti successivi che sono vicini al ritmo target.',
'': 'Interruttore del piede',
'': 'Interruttore del piede abilitato.',
'': 'Interruttore del piede disabilitato.',
'': 'Quando l\'interruttore del piede è abilitato, è possibile abilitare o disabilitare i battiti spostando rapidamente il piede su entrambi i lati mentre è piatto sul pavimento.',
'': 'BPM dovrebbe essere 180 o meno.',
'': 'BPM dovrebbe essere 40 o più.',
'': 'In modalità insolita, i suoni vengono suonati tra i battiti. I battiti sono mostrati in blu e insoliti in viola.',
'': 'Angolo',
'': 'Metronomo',
'': 'Se abilitato, verrà riprodotto un tono al tempo selezionato.',
'': 'Mostra politica sulla privacy',
'': 'Modalità automatica',
'': 'Modalità automatica abilitata.',
'': 'Modalità automatica disabilitata.',
'': 'Quando la modalità automatica è abilitata, in modalità 1-TAP devi solo toccare il piede sul primo 1 e il groove gioca automaticamente.',
},
'pt': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Conectar',
'': 'desconectar',
'': 'MODO',
'': 'Modo de reprodução',
'': 'NOTAS',
'': '1ª nota',
'': '2ª nota',
'': 'Happy Feet - Grooves',
'': 'Defina o ritmo',
'': 'Batidas/medida',
'': 'Medidas',
'': 'Vozes',
'': '1',
'': '2',
'': 'Backbeat',
'': 'O modo exclusivo pode ser usado apenas com o número par de batidas por medida.',
'': ' Escolha "-" sem nota, b para bumbo, b para baixo eco, t para baixo tom, t para alto tom, s para bateria de armadilha, h para o chimbal de chimbal Fingersnap, r para aro tiro, a para shaker, w para Woodblock, q para quijada, u para pincéis',
'': 'Salve o ritmo',
'': 'Groove de carga',
'': 'Nenhuma ranhura salva encontrada.',
'': 'Happy Feet - Bass',
'': 'Defina o ritmo de baixo',
'': 'Chave de',
'': 'Tons:',
'': 'Escolha "-" sem nota, ou números de 1 a 7 mais apartamentos para tons',
'': 'Não configurado',
'': 'Happy Feet - Menu Info',
'': 'Número do modelo:',
'': 'Resultado:',
'': 'Erro:',
'': 'Aguardando resultado',
'': 'Mostre a página inicial do Happyfeet',
'': 'Happy Feet - menu de configurações',
'': 'Sensibilidade',
'': 'Menos',
'': 'Mais',
'': 'Você deve estar conectado para ajustar.',
'': 'Redefinir sensibilidade ao padrão',
'': 'Você deve estar conectado à redefinição ao padrão.',
'': 'Happy Feet - salvar groove',
'': 'Digite o nome da ranhura:',
'': 'Digite uma descrição do ritmo:',
'': 'Happy Feet - Grove de carga',
'': 'Grooves salvos:',
'': 'Ranhura carregada',
'': 'Status de carga',
'': 'Nome do arquivo ausente ou inválido:',
'': 'Perceber',
'': 'Status',
'': 'já conectado',
'': 'O modo de batida traseira só pode ser usado com o número par de batidas por medida.',
'': 'batidas desativadas',
'': 'batidas ativadas',
'': 'Conecte -se ao Bluetooth primeiro',
'': 'conectando ao Bluetooth',
'': 'Desconectando o Bluetooth',
'': 'Groove salvo',
'': 'não conectado',
'': 'Nota única',
'': 'Notas alternadas',
'': 'Notas duplas',
'': 'Groove',
'': 'Graves',
'': 'Erro de sequência:',
'': 'Uma batida foi perdida, possivelmente devido a uma mensagem de notificação de Bluetooth perdida',
'': 'Status Bluetooth',
'': 'Este dispositivo não suporta Bluetooth',
'': 'Autorize o aplicativo Happyfeet para usar o Bluetooth e a localização',
'': 'O Bluetooth está desligado. Por favor, ligue',
'': 'Ativar serviços de localização',
'': 'Encontrado Happy Feet! Conectando',
'': 'Não consigo encontrar Happy Feet! Você possui um? Está nas proximidades? É cobrado?',
'': 'Conectado!',
'': 'A conexão falhou com o erro',
'': 'Desconectando',
'': 'Mudar idioma',
'': 'Revisão de firmware:',
'': 'Desconectando, já que nenhuma batida é detectada por 30 minutos',
'': 'Modo de teste de áudio',
'': 'Você não pode usar o modo de teste de áudio se conectado.',
'': 'Modo de teste de áudio ativado.',
'': 'Modo de teste de áudio desativado.',
'': 'No modo de teste de áudio, toque no botão Music Note para reproduzir a próxima nota.',
'': 'Carregando sons de percussão.',
'': 'Carregando sons de graves.',
'': 'Modo 1-TAP: Escolha um ritmo, ative batidas, toque no pé 4 vezes como um concurso e depois apenas nos 1s',
'': 'Modo 1-TAP: Escolha um ritmo, Ative Beats, toque o pé 4 vezes como um concurso e depois apenas no primeiro 1',
'': 'Comprimido',
'': 'A comprimido é uma forma simplificada de notação musical. Consulte www.drumtabs.org para obter mais detalhes.',
'': 'Contagem de chumbo:',
'': 'Happyfeet - menu 1 -TAP',
'': 'Ritmo',
'': 'Ritmo 1-TAP: rock1',
'': 'Ritmo 1-TAP: rock2',
'': 'Ritmo 1-TAP: Jazz1',
'': 'Ritmo 1-TAP: Bossa Nova',
'': 'Ritmo 1-TAP: Merengue',
'': 'Ritmo 1-TAP: Afro-Cuban 6/8',
'': 'Ritmo 1-TAP: Samba',
'': 'Ritmo 1-TAP: Salsa',
'': 'Número de série:',
'': 'Modo multi',
'': 'Modo multi ativado.',
'': 'Modo multi desativado.',
'': 'Use Multi Mode se você tiver mais de um Happyfeet.',
'': 'Happyfeet - Multi -Connect',
'': 'Selecione um happyfeet disponível:',
'': 'Happyfeet nas proximidades está listado do mais próximo ao mais longe, como mostrado por RSSI',
'': 'Nível de carga da bateria:',
'': 'Pé ativo/Desativar recebido',
'': 'Prática',
'': 'Happy Feet - Menu Prática',
'': 'Som',
'': 'Tempo [BPM]',
'': 'Batidas ativadas pelo pé',
'': 'Batidas desativadas pelo pé',
'': 'Escolha um som, defina o ritmo, ative batidas e toque no seu pé.',
'': 'Tempo medido:',
'': 'Contagem de faixas:',
'': 'Número de batidas sucessivas próximas ao ritmo alvo.',
'': 'Interruptor do pé',
'': 'Interruptor do pé ativado.',
'': 'Interruptor do pé desativado.',
'': 'Quando o interruptor do pé estiver ativado, você pode ativar ou desativar batidas movendo o pé rapidamente para ambos os lados enquanto está no chão.',
'': 'O BPM deve ter 180 ou menos.',
'': 'O BPM deve ter 40 ou mais.',
'': 'No modo excêntrico, os sons são tocados entre as batidas. As batidas são mostradas em azul e fora do roxo.',
'': 'Ângulo',
'': 'Metrônomo',
'': 'Quando ativado, um tom será reproduzido no ritmo selecionado.',
'': 'Mostrar política de privacidade',
'': 'Modo automático',
'': 'Modo automático ativado.',
'': 'Modo automático desativado.',
'': 'Quando o modo automático é ativado, no modo 1-TAP, você só precisa tocar no seu pé no primeiro 1 e o sulco é reproduzido automaticamente.',
},
'nl': {
'': 'Happy Feet',
'': 'BLUETOOTH',
'': 'Aansluiten',
'': 'verbinding verbreken',
'': 'Modus',
'': 'Speelmodus',
'': 'Aantekeningen',
'': '1e noot',
'': '2e noot',
'': 'Gelukkige voeten - grooves',
'': 'Definieer groove',
'': 'Beats/maatregel',
'': 'Maatregelen',
'': 'Stemmen',
'': '1',
'': '2',
'': 'Backbeat',
'': 'Offbeat -modus kan alleen worden gebruikt met een even aantal beats per maat.',
'': ' Kies "-" zonder opmerking, b voor basdrum, b voor bas echo, t voor lage tom, t voor hoge tom, s voor snaredrum, h voor hi-hat cymbal, m voor tambourine, c voor cowbell, f voor Fingersnap, r voor Rim Shot, A voor Shaker, W voor Woodblock, Q voor Quijada, U voor borstels',
'': 'Bewaar groove',
'': 'Laadgroef',
'': 'Geen opgeslagen grooves gevonden.',
'': 'Gelukkige voeten - bas',
'': 'Definieer basgroef',
'': 'Sleutel van',
'': 'Tonen:',
'': 'Kies "-" voor geen notitie, of nummers 1 tot en met 7 plus flats voor tonen',
'': 'Niet ingesteld',
'': 'Happy Feet - Info -menu',
'': 'Modelnummer:',
'': 'Resultaat:',
'': 'Fout:',
'': 'In afwachting van resultaat',
'': 'Toon HappyFeet Homepage',
'': 'Happy Feet - Instellingenmenu',
'': 'Gevoeligheid',
'': 'Minder',
'': 'Meer',
'': 'U moet zijn verbonden om aan te passen.',
'': 'Reset de gevoeligheid tot standaard',
'': 'U moet zijn verbonden om opnieuw in te stellen naar standaard.',
'': 'Happy Feet - Bespaar Groove',
'': 'Voer de Groove -naam in:',
'': 'Voer een beschrijving van de groove in:',
'': 'Happy Feet - Load Groove',
'': 'Opgeslagen grooves:',
'': 'Geladen groove',
'': 'Laadstatus',
'': 'Ontbrekende of ongeldige bestandsnaam:',
'': 'Merk op',
'': 'Toestand',
'': 'Al verbonden',
'': 'Back Beat -modus kan alleen worden gebruikt met een even aantal beats per maat.',
'': 'Beats uitgeschakeld',
'': 'Beats ingeschakeld',
'': 'Maak eerst verbinding met Bluetooth',
'': 'Verbinding maken met Bluetooth',
'': 'Bluetooth loskoppelen',
'': 'groove opgeslagen',
'': 'niet verbonden',
'': 'Enkele notitie',
'': 'Afwisselende opmerkingen',
'': 'Dubbele opmerkingen',
'': 'Groef',
'': 'Bas',
'': 'Sequentiefout:',
'': 'Een beat werd gemist, mogelijk vanwege een verloren Bluetooth -meldingsbericht',
'': 'Bluetooth -status',
'': 'Dit apparaat ondersteunt geen Bluetooth',
'': 'Machtig de happyfeet -app om Bluetooth en locatie te gebruiken',
'': 'Bluetooth is uitgeschakeld. Schakel het in',
'': 'Locatiediensten inschakelen',
'': 'Happy Feet gevonden! Verbinden',
'': 'Geen happyfeet gevonden! Heb je er een? Is het in de buurt? Is het opgeladen?',
'': 'Verbonden!',
'': 'Verbinding mislukt met fout',
'': 'Loskoppeling',
'': 'Verander taal',
'': 'Firmware -herziening:',
'': 'Loskoppelen omdat er geen beats gedurende 30 minuten is gedetecteerd',
'': 'Audiotestmodus',
'': 'U kunt de audiotestmodus niet gebruiken als u is aangesloten.',
'': 'Audiotestmodus ingeschakeld.',
'': 'Audiotestmodus uitgeschakeld.',
'': 'Tik in de audiotestmodus op de knop Muzieknotities om de volgende noot te spelen.',
'': 'Percussion Sounds laden.',
'': 'Basgeluiden laden.',
'': '1-TAP-modus: kies een ritme, schakel beats in, tik 4 keer op je voet als een telling en vervolgens alleen op de 1s',
'': '1-TAP-modus: kies een ritme, schakel beats in, tik 4 keer op je voet als een telling en vervolgens alleen op de eerste 1',
'': 'Tabel',
'': 'Tablatuur is een vereenvoudigde vorm van muzieknotatie. Zie www.drumtabs.org voor meer informatie.',
'': 'Leid-in-telling:',
'': 'Happyfeet - 1 -tap menu',
'': 'Ritme',
'': '1-tap ritme: rock1',
'': '1-tap ritme: rock2',
'': '1-tap ritme: jazz1',
'': '1-Tap Rhythm: Bossa Nova',
'': '1-tap ritme: merengue',
'': '1-tap ritme: Afro-Cuban 6/8',
'': '1-tap ritme: samba',
'': '1-tap ritme: salsa',
'': 'Serienummer:',
'': 'Multi -modus',
'': 'Multi -modus ingeschakeld.',
'': 'Multi -modus uitgeschakeld.',
'': 'Gebruik multi -modus als u meer dan één happyfeet hebt.',
'': 'Happyfeet - multi -connect',
'': 'Selecteer een beschikbare happyfeet:',
'': 'Nabijgelegen happyfeet worden vermeld van het dichtst bij het verst',
'': 'Batterij oplaadniveau:',
'': 'Voet inschakelen/uitschakelen ontvangen',
'': 'Oefening',
'': 'Happy Feet - Oefenmenu',
'': 'Geluid',
'': 'Tempo [bpm]',
'': 'Beats te voet ingeschakeld',
'': 'Beats te voet uitgeschakeld',
'': 'Kies een geluid, stel het tempo in, schakel beats in en tik op je voet.',
'': 'Gemeten tempo:',
'': 'Streak Count:',
'': 'Aantal opeenvolgende beats die dicht bij het doeltempo liggen.',
'': 'Voetschakelaar',
'': 'Voetschakelaar ingeschakeld.',
'': 'Voetschakelaar uitgeschakeld.',
'': 'Wanneer de voetschakelaar is ingeschakeld, kunt u beats in- of uitschakelen door uw voet snel naar beide kanten te bewegen terwijl u plat op de vloer bent.',
'': 'BPM moet 180 of minder zijn.',
'': 'BPM moet 40 of meer zijn.',
'': 'In de ongebruikelijke modus worden geluiden gespeeld tussen Beats. Beats worden in blauwe en offbeats getoond in paars.',
'': 'Hoek',
'': 'Metronoom',
'': 'Wanneer ingeschakeld, wordt een toon gespeeld in het geselecteerde tempo.',
'': 'Toon privacybeleid',
'': 'Automatische modus',
'': 'Auto -modus ingeschakeld.',
'': 'Auto -modus uitgeschakeld.',
'': 'Wanneer de Auto-modus is ingeschakeld, hoeft u in 1-tap-modus alleen op uw voet op de eerste 1 te tikken en speelt de groef automatisch.',
},
'uk': {
'': 'Happy Feet',
'': 'Bluetooth',
'': 'З\'єднувати',
'': 'Відключити',
'': 'Режим',
'': 'Режим гри',
'': 'Нотатки',
'': '1 -а примітка',
'': '2 -а нота',
'': 'Щасливі ноги - канавки',
'': 'Визначте канавку',
'': 'Удари/міра',
'': 'Заходи',
'': 'Голоси',
'': '1',
'': '2',
'': 'Зворотний бік',
'': 'Невимірний режим можна використовувати лише з парною кількістю ударів за міру.',
'': ' Виберіть "-" Без замітки, B для басового барабана, B для басового ехо, T для низького TOM, T для високого TOM, S для барабанного барабана, H для Cymbal Hi-Hat, M для бубну, C для Cowbell, F для Fingersnap, R для Rim Shot, A для шейкера, W для деревного блок, Q для Quijada, u для пензлів',
'': 'Зберегти канавку',
'': 'Навантажувати канавку',
'': 'Збережених канавок не знайдено.',
'': 'Щасливі ноги - бас',
'': 'Визначте бас -канавку',
'': 'Ключ',
'': 'Тони:',
'': 'Виберіть "-" Без ноти, або цифри 1-7 плюс квартири для тонів',
'': 'Не встановлено',
'': 'Щасливі ноги - Інформаційне меню',
'': 'Номер моделі:',
'': 'Результат:',
'': 'Помилка:',
'': 'Очікуючи результат',
'': 'Показати Happyfeet домашню сторінку',
'': 'Щасливі ноги - меню налаштувань',
'': 'Чутливість',
'': 'Менше',
'': 'Більше',
'': 'Ви повинні бути підключені для регулювання.',
'': 'Скидання чутливості до за замовчуванням',
'': 'Ви повинні бути підключені до скидання за замовчуванням.',
'': 'Щасливі ноги - Збережіть канавку',
'': 'Введіть назву Groove:',
'': 'Введіть опис канавки:',
'': 'Щасливі ноги - навантаження',
'': 'Збережено канавки:',
'': 'Завантажений канавка',
'': 'Стан завантаження',
'': 'Відсутнє або недійсне ім\'я файлу:',
'': 'Ув\'язнення',
'': 'Статус',
'': 'вже підключений',
'': 'Режим зворотного удару можна використовувати лише з парною кількістю ударів за міру.',
'': 'BEATS інвалідом',
'': 'Увімкнено удари',
'': 'Спочатку підключіться до Bluetooth',
'': 'Підключення до Bluetooth',
'': 'Від\'єднання Bluetooth',
'': 'врятував канавку',
'': 'не під\'єднано',
'': 'Єдина нота',
'': 'Чергуючі нотатки',
'': 'Подвійні нотатки',
'': 'Паз',
'': 'Окунь',
'': 'Помилка послідовності:',
'': 'Удар було пропущено, можливо, через втрачене повідомлення про сповіщення Bluetooth',
'': 'Статус Bluetooth',
'': 'Цей пристрій не підтримує Bluetooth',
'': 'Дозволити додаток HappyFeet використовувати Bluetooth та місцезнаходження',
'': 'Bluetooth вимкнено. Будь ласка, увімкніть його',
'': 'Увімкнути послуги розташування',
'': 'Знайдено щасливі ноги! Підключення',
'': 'Жодного Happyfeet не знайшов! Ви володієте? Це поблизу? Це стягується?',
'': 'Підключено!',
'': 'Підключення не вдалося з помилкою',
'': 'Від\'єднання',
'': 'Змінити мову',
'': 'Перегляд прошивки:',
'': 'Від\'єднання, оскільки не виявлено ударів протягом 30 хвилин',
'': 'Режим аудіо тестування',
'': 'Ви не можете використовувати режим аудіо -тестування, якщо підключитися.',
'': 'Увімкнено режим аудіо тестування.',
'': 'Режим аудіо тестування відключений.',
'': 'У режимі аудіо -тестування натисніть кнопку Music Note, щоб відтворити наступну ноту.',
'': 'Завантаження ударних звуків.',
'': 'Завантаження звуків басів.',
'': 'Режим 1-TAP: Виберіть ритм, увімкнути удари, натисніть на ногу 4 рази як підрахунок, а потім лише на 1s',
'': 'Режим 1-TAP: Виберіть ритм, увімкнути удари, натисніть на ногу 4 рази як підрахунок, а потім лише на першому 1',
'': 'Таблатура',
'': 'Таблиці - це спрощена форма музичної нотації. Докладніше див. У www.drumtabs.org.',
'': 'Ведучий підрахунок:',
'': 'Happyfeet - 1 -TAP меню',
'': 'Ритм',
'': 'Ритм 1-TAP: Rock1',
'': 'Ритм 1-TAP: Rock2',
'': 'Ритм 1-TAP: Джаз1',
'': 'Ритм 1-TAP: Bossa Nova',
'': 'Ритм 1-TAP: Меренге',
'': 'Ритм 1-TAP: Афро-Кубан 6/8',
'': 'Ритм 1-TAP: Самба',
'': 'Ритм 1-TAP: сальса',
'': 'Серійний номер:',
'': 'Багато режиму',
'': 'Увімкнено багато режиму.',
'': 'Багато режиму вимкнено.',
'': 'Використовуйте мульти режиму, якщо у вас є більше одного Happyfeet.',
'': 'Happyfeet - Multi -Connect',
'': 'Виберіть доступний HappyFeet:',
'': 'Поблизу HappyFeet перераховані від найближчого до найдалі, як показано RSSI',
'': 'Рівень заряду акумулятора:',
'': 'Увімкнути/вимкнути отримані',
'': 'Практикувати',
'': 'Щасливі ноги - меню практики',
'': 'Звук',
'': 'Темп [BPM]',
'': 'Удари ввімкнено пішки',
'': 'Бит інваліди пішки',
'': 'Виберіть звук, встановіть темп, увімкніть удари та торкніться ноги.',
'': 'Вимірюваний темп:',
'': 'Кількість смуг:',
'': 'Кількість послідовних ударів, близьких до цільового темпу.',
'': 'Ножний перемикач',
'': 'Увімкнено перемикач ніг.',
'': 'Вимкнено перемикач ніг.',
'': 'Коли перемикач ноги увімкнено, ви можете включити або відключити удари, швидко перемістивши стопу в будь -яку сторону, коли плоскі на підлозі.',
'': 'BPM повинен бути 180 або менше.',
'': 'BPM має бути 40 і більше.',
'': 'У неперевершеному режимі звуки відтворюються між ударами. Убивки показані синім кольором і неперевершеними у фіолетовому кольорі.',
'': 'Кут',
'': 'Метроном',
'': 'Якщо ввімкнути, в вибраному темпі буде відтворюватися тон.',
'': 'Політика конфіденційності проявляти',
'': 'Автоматичний режим',
'': 'Автоматичний режим увімкнено.',
'': 'Автоматичний режим відключений.',
'': 'Коли автоматичний режим увімкнено, в режимі 1-TAP вам доведеться лише натискати на ногу на першому 1, а канавка грає автоматично.',
},
        };
      }
      