var sf2Map = <String, num>{
   'Kick Sweet Tite':36,
   'Rim Shot':37,
   'Tight Snare':38,
   'Dry Ring Snare':39,
   'Snare Nicey':40,
   'Low Dry Tom':41,
   'Lite Hat Tight':42,
   'Low Dry Tom':43,
   'Lite Hat Tight':44,
   'Hi Dry Tom':45,
   'Lite Hat Open':46,
   'Hi Dry Tom':47,
   'Hi Dry Tom':48,
   'Cymbal 14" Crash':     49,
   'Hi Dry Tom':50,
   'Ride Ping':51,
   'Snare Roll':52,
   'Ride Bell':53,
   'Triple Roll':54,
   'Cymbal 12" Splash':    55,
   'Stick Start':56,
   'Cymbal 14" Crash':     57,
   'Fingersnap':58,
   'Kick Sweet Tite':59,
   'Lite Hat Open':59,
   'Fat Kick':60,
   'Side Stick':61,
   'Snare Rim Mono':62,
   'Snare Gated Rvrb':     63,
   'Tight Snare':63,
   'Snare Nicey':64,
   'Snare Rim Mono':64,
   'Hit Tom Attack':65,
   'Low Dry Tom':65,
   'HH Foot':66,
   'Hit Tom Attack':67,
   'Low Dry Tom':67,
   'HH Foot':68,
   'Hi Dry Tom':69,
   'Hit Tom Attack':69,
   'HH Open':70,
   'Hi Dry Tom':71,
   'Hit Tom Attack':72,
   'Hi Dry Tom':72,
   'Hit Tom Attack':72,
   'Cymbal 14" Crash':     73,
   'Hi Dry Tom':74,
   'Hit Tom Attack':74,
   'Ride Ping':75,
   'Tam Tam':76,
   'Ride Bell':77,
   'Tambourine':78,
   'Cymbal 12" Splash':79,
   'Cowbell':80,
   'Cymbal 14" Crash':81,
   'Fingersnap':82,
   'Cymbal 14" Crash':83,
   'Fat Kick':83,
};
